# Generated by Django 5.2.6 on 2025-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Статус оплаты Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет'), ('stripe', 'Stripe')], max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
