# Generated by Django 5.2.6 on 2025-09-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_updated_at_subscription_is_active'),
    ]

    operations = [
    ]
